### ISSUE TITLE
Strange look 

### ISSUE THREAD

**Issue by dsever** [Patrowl/PatrowlManager#30] opened 2018-11-21 14:27 UTC
Hi,

For purpose of PoC when building from Dockerfile it gives me strange look, like it is some kind of debug mode or what.
![screenshot from 2018-11-21 15-26-14](https://user-images.githubusercontent.com/7211879/48847437-d68ecb00-eda1-11e8-8ef4-d9420b609361.png)

Thanks
Dubravko

**Comment by MaKyOtOx** [comment] 2018-11-21 15:19
Hi, 
The static files seems to be not loaded. Did you used the docker-compose (recommended, because it includes the nginx RP ^^) or just run the docker image ?

**Comment by MaKyOtOx** [comment] 2018-11-21 16:48
I've reproduced and confirmed the issue. It's now fixed. 
Thank you very much for the report :)

**Comment by dsever** [comment] 2018-11-21 18:19
Looks good for for now for testing purpose, later I will try to optimize docker-compose.
Please be free to close issue.

**Comment by MaKyOtOx** [comment] 2018-11-22 17:33
Perfect :)

**Closed by MaKyOtOx** 2018-11-22 17:33 UTC
Labels: bug

**Comment by psantos1** [comment] 2018-12-11 09:36
Hi,

Just letting you know that I've recently installed PatrowlManager, and I was getting the same view.
I am not using docker, the problem was that the nginx.conf file was redirecting every request that came with /static/ to /staticfiles/, removing it fixed the problem.

Regards
